services:
  app:
    build: .
    restart: always
    container_name: blog-app
    environment:
      POSTGRES_URL: db
      DATABASE_USERNAME: luan
      DATABASE_PASSWORD: example
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: luan
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"